# Generated by Django 2.1.5 on 2024-03-13 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GUFilmmakingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehindTheScene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='file_path')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('video', models.FileField(upload_to='videos_uploaded')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='posters/')),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='poster',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUFilmmakingApp.Category'),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUFilmmakingApp.Category'),
        ),
        migrations.AddField(
            model_name='behindthescene',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUFilmmakingApp.Category'),
        ),
    ]
