# Generated by Django 2.1.5 on 2024-03-14 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GUFilmmakingApp', '0002_auto_20240313_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('year', models.CharField(max_length=7)),
                ('post_type', models.CharField(choices=[('movie', 'Movie'), ('poster', 'Poster'), ('bts', 'Behind the Scenes')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUFilmmakingApp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('profileImage', models.ImageField(upload_to='')),
                ('verified', models.BooleanField(default=False)),
                ('bio', models.CharField(max_length=200)),
                ('myLikes', models.ManyToManyField(blank=True, related_name='liked_by', to='GUFilmmakingApp.Post')),
                ('myPosts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='GUFilmmakingApp.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='behindthescene',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='category',
        ),
        migrations.DeleteModel(
            name='BehindTheScene',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Poster',
        ),
    ]
