# Generated by Django 2.1.5 on 2024-03-14 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GUFilmmakingApp', '0003_auto_20240314_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUFilmmakingApp.UserProfile'),
        ),
    ]
