# Generated by Django 2.1.5 on 2024-03-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUFilmmakingApp', '0005_behindthescene_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behindthescene',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='category',
        ),
        migrations.DeleteModel(
            name='BehindTheScene',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Poster',
        ),
    ]
