# Generated by Django 2.1.5 on 2024-03-18 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUFilmmakingApp', '0006_auto_20240318_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='year',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('shorter_movie', 'Shorter Movie'), ('longer_movie', 'Longer Movie'), ('poster', 'Poster'), ('bts', 'Behind the Scenes')], max_length=20),
        ),
    ]
