# Generated by Django 5.0.3 on 2024-03-19 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GUFilmmakingApp", "0008_alter_post_likes_alter_post_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                upload_to="media/thumbnails/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
