# Generated by Django 4.2.11 on 2024-03-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUFilmmakingApp', '0010_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
