# Generated by Django 5.0.3 on 2024-03-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GUFilmmakingApp", "0011_remove_post_category_delete_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="slug",
            field=models.SlugField(default="hold", unique=True),
            preserve_default=False,
        ),
    ]
