# Generated by Django 4.2.11 on 2024-03-21 09:50

import GUFilmmakingApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUFilmmakingApp', '0013_auto_20240320_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(default='hold', upload_to=GUFilmmakingApp.models.PathAndRename('content')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=GUFilmmakingApp.models.PathAndRename('thumbnails'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(default='/default_user_profile.jpg', upload_to='profileImage'),
        ),
    ]
